FROM golang:latest
RUN apk update && apk add --no-cache make gcc musl-dev zip wget curl

RUN mkdir /app

WORKDIR /app

COPY . .

RUN go mod download

RUN make release

#FROM alpine:latest AS final
#COPY --from=build-app /app/build/linux-amd64/monstache /bin/monstache
#ENTRYPOINT ["/bin/monstache"]
#COPY --from=build-app /app/build/plugin.so /bin/plugin.so`
