FROM golang:latest
RUN apk add --no-cache gcc musl-dev

WORKDIR /app
COPY . .
RUN go mod download
RUN ls -R

#FROM alpine:latest AS final
#ENTRYPOINT ["/bin/monstache"]
#COPY --from=build-app /app/build/linux-amd64/monstache /bin/monstache
#COPY --from=build-app /app/build/plugin.so /bin/plugin.so`
